### ISSUE TITLE
Avoid use of spaces in file or directory names

### ISSUE THREAD

**Issue by sdhunt** [GuessWhatItsSteve/prj-rev-bwfs-dasmoto#6]
I noticed that you named your project directory "Dasmoto Arts and Crafts". 

Although operating systems allow this, it is strongly advised that you avoid using spaces in file or directory names.. usually because dealing with them correctly in the Command Line, or in scripts, can turn out to be a _pain in the proverbial_.

Here's an article that explores this issue:
https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names

**Comment by GuessWhatItsSteve** [comment]
Ah, good to know. I didn't realize that. Thanks!
