### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [GuessWhatItsSteve/prj-rev-bwfs-dasmoto#7]
_Grade:_ __Meets Expectations__

On the whole, a solid project submission.
* You met the specification
  * Your page rendered an accurate representation of the spec
  * This is always a good goal to have
* You correctly used identifiers (`id`) and classes (`class`), making your code neat and concise.

Some areas to improve:
* Break up the "block" of source code with judicial use of blank lines and comments
* Introduce `<div>` elements to group together elements that belong to the same "item"
* Don't forget to define the `alt` attribute on `<img>` tags; for accessability
* Remember you can use the "global" selector to apply style(s) to every element in the document

For further study:
https://www.smashingmagazine.com/2008/11/12-principles-for-keeping-your-code-clean/
https://learn.shayhowe.com/html-css/writing-your-best-code/

Keep up the great work!

**Comment by GuessWhatItsSteve** [comment]
Sounds good, thank you!
